package gogen

import (
	"fmt"
	"strings"

	"github.com/jptrs93/cleanproto/internal/ir"
)

func buildGoAuditFile(file ir.File, msgs map[string]ir.Message, enums map[string]ir.Enum, pkg, tags string, keep map[string]bool) ([]byte, error) {
	needs := computeAuditMessages(file, msgs)
	auditIndex := map[string]ir.Message{}
	for full, m := range msgs {
		if needs[full] {
			m.Name = "Audit" + m.Name
		}
		auditIndex[full] = m
	}
	var auditFile ir.File
	var body strings.Builder
	for _, m := range file.Messages {
		if !needs[m.FullName] || (keep != nil && !keep[m.FullName]) {
			continue
		}
		am := auditIndex[m.FullName]
		am.Fields = nil
		for _, f := range goVisibleFields(m.Fields) {
			if !f.AuditIgnore {
				am.Fields = append(am.Fields, f)
			}
		}
		auditFile.Messages = append(auditFile.Messages, am)
		fmt.Fprintf(&body, "type %s struct {\n", am.Name)
		for _, f := range am.Fields {
			if f.OneofName != "" {
				continue
			}
			typ, _, err := goFieldType(f, auditIndex, enums)
			if err != nil {
				return nil, err
			}
			tag := auditJSONTag(f, tags)
			fmt.Fprintf(&body, "%s %s%s\n", ir.GoName(f.Name), typ, tag)
		}
		for _, group := range am.Oneofs {
			typ := oneofType(am, group.Name)
			if !group.Required {
				typ = "Maybe[" + typ + "]"
			}
			tag := ""
			if tags == "snake" {
				tag = " `json:\"" + group.Name + ",omitzero\"`"
			}
			fmt.Fprintf(&body, "%s %s%s\n", ir.GoName(group.Name), typ, tag)
		}
		body.WriteString("}\n")
		fmt.Fprintf(&body, "func (m *%s) ToAudit() *%s {\nif m == nil { return nil }; out := &%s{}\n", m.Name, am.Name, am.Name)
		for _, f := range am.Fields {
			if f.OneofName != "" {
				continue
			}
			emitAuditAssignment(&body, "out."+ir.GoName(f.Name), "m."+ir.GoName(f.Name), f, needs, auditIndex, enums)
		}
		for _, group := range m.Oneofs {
			n := ir.GoName(group.Name)
			if group.Required {
				fmt.Fprintf(&body, "{ choice := m.%s\n", n)
			} else {
				fmt.Fprintf(&body, "if m.%s.Present { choice := m.%s.Value\n", n, n)
			}
			fmt.Fprintf(&body, "_ = choice\nvar projected %s\n", oneofType(am, group.Name))
			for _, f := range am.Fields {
				if f.OneofName == group.Name {
					emitAuditAssignment(&body, "projected."+ir.GoName(f.Name), "choice."+ir.GoName(f.Name), f, needs, auditIndex, enums)
				}
			}
			if group.Required {
				fmt.Fprintf(&body, "out.%s = projected\n}\n", n)
			} else {
				fmt.Fprintf(&body, "out.%s = Maybe[%s]{Value: projected, Present: true}\n}\n", n, oneofType(am, group.Name))
			}
		}
		body.WriteString("return out\n}\n")
	}
	if len(auditFile.Messages) == 0 {
		return nil, nil
	}
	choices, err := buildChoiceSource(auditFile, auditIndex, enums, tags, true)
	if err != nil {
		return nil, err
	}
	body.WriteString(choices)
	var out strings.Builder
	fmt.Fprintf(&out, "// Code generated by cleanproto. DO NOT EDIT.\npackage %s\n", pkg)
	if strings.Contains(body.String(), "time.") {
		out.WriteString("import \"time\"\n")
	}
	if strings.Contains(body.String(), "uuid.") {
		out.WriteString("import \"github.com/google/uuid\"\n")
	}
	if strings.Contains(body.String(), "json.") {
		out.WriteString("import \"encoding/json\"\n")
	}
	out.WriteString(body.String())
	return []byte(out.String()), nil
}
func auditJSONTag(f ir.Field, tags string) string {
	if f.JSONIgnore {
		return " `json:\"-\"`"
	}
	if tags != "snake" {
		return ""
	}
	tag := toSnakeCase(f.Name)
	if goMaybeField(f) {
		tag += ",omitzero"
	} else if goJSONTagOmitEmpty(f) {
		tag += ",omitempty"
	}
	return " `json:\"" + tag + "\"`"
}
func emitAuditAssignment(b *strings.Builder, dst, src string, f ir.Field, needs map[string]bool, msgs map[string]ir.Message, enums map[string]ir.Enum) {
	target := validateMessageTarget(f)
	if !needs[target] {
		fmt.Fprintf(b, "%s = %s\n", dst, src)
		return
	}
	switch {
	case f.IsMap:
		typ, _, _ := goFieldType(f, msgs, enums)
		fmt.Fprintf(b, "if %s != nil { %s = make(%s, len(%s)); for k,v := range %s { %s[k] = *v.ToAudit() } }\n", src, dst, typ, src, src, dst)
	case f.IsRepeated:
		typ, _, _ := goFieldType(f, msgs, enums)
		fmt.Fprintf(b, "if %s != nil { %s = make(%s, 0, len(%s)) }; for _,v := range %s {\n", src, dst, typ, src, src)
		if goRepeatedValueSlice(f) {
			fmt.Fprintf(b, "%s = append(%s, *v.ToAudit())\n", dst, dst)
		} else {
			fmt.Fprintf(b, "%s = append(%s, v.ToAudit())\n", dst, dst)
		}
		b.WriteString("}\n")
	case f.OneofName != "":
		fmt.Fprintf(b, "%s = %s.ToAudit()\n", dst, src)
	case goMaybeField(f):
		typ, _, _ := goFieldType(f, msgs, enums)
		if f.GoIndirect {
			fmt.Fprintf(b, "if %s.Present { v := %s.Value; %s = %s{Value: v.ToAudit(), Present: true} }\n", src, src, dst, typ)
		} else {
			fmt.Fprintf(b, "if %s.Present { v := %s.Value; %s = %s{Value: *v.ToAudit(), Present: true} }\n", src, src, dst, typ)
		}
	default:
		if f.GoIndirect {
			fmt.Fprintf(b, "%s = %s.ToAudit()\n", dst, src)
		} else {
			fmt.Fprintf(b, "%s = *%s.ToAudit()\n", dst, src)
		}
	}
}
