package gogen

import (
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/jptrs93/cleanproto/internal/ir"
)

func buildGoValidateFile(file ir.File, msgIndex map[string]ir.Message, enumIndex map[string]ir.Enum, needs map[string]bool, pkg string) ([]byte, error) {
	if len(needs) == 0 {
		return nil, nil
	}
	hasAny := false
	for _, msg := range file.Messages {
		if needs[msg.FullName] {
			hasAny = true
			break
		}
	}
	if !hasAny {
		return nil, nil
	}
	g := &validateGen{
		msgIndex:     msgIndex,
		enumIndex:    enumIndex,
		needs:        needs,
		patternIndex: map[string]string{},
	}
	var bodies strings.Builder
	for _, msg := range file.Messages {
		if !needs[msg.FullName] {
			continue
		}
		if err := g.emitValidate(&bodies, msg); err != nil {
			return nil, fmt.Errorf("%s.Validate: %w", msg.Name, err)
		}
	}

	var out strings.Builder
	out.WriteString("// Code generated by cleanproto. DO NOT EDIT.\n\n")
	out.WriteString("package ")
	out.WriteString(pkg)
	out.WriteString("\n\n")

	imports := []string{}
	if g.needBytes {
		imports = append(imports, "bytes")
	}
	if g.needFmt {
		imports = append(imports, "fmt")
	}
	if g.needNetMail {
		imports = append(imports, "net/mail")
	}
	if g.needRegexp {
		imports = append(imports, "regexp")
	}
	if g.needSlices {
		imports = append(imports, "slices")
	}
	if g.needStrings {
		imports = append(imports, "strings")
	}
	if g.needUTF8 {
		imports = append(imports, "unicode/utf8")
	}
	sort.Strings(imports)
	if len(imports) > 0 {
		out.WriteString("import (\n")
		for _, imp := range imports {
			out.WriteString("\t\"")
			out.WriteString(imp)
			out.WriteString("\"\n")
		}
		out.WriteString(")\n\n")
	}
	if g.needUUID {
		out.WriteString(uuidValidatorSnippet)
		out.WriteString("\n")
	}
	if len(g.patterns) > 0 {
		for _, p := range g.patterns {
			out.WriteString("var ")
			out.WriteString(p.Var)
			out.WriteString(" = regexp.MustCompile(`")
			out.WriteString(p.Pattern)
			out.WriteString("`)\n")
		}
		out.WriteString("\n")
	}
	out.WriteString(bodies.String())
	return []byte(out.String()), nil
}

const uuidValidatorSnippet = `func validateUUIDFormat(s string) bool {
	if len(s) != 36 {
		return false
	}
	for i := 0; i < 36; i++ {
		c := s[i]
		switch i {
		case 8, 13, 18, 23:
			if c != '-' {
				return false
			}
		default:
			if !(('0' <= c && c <= '9') || ('a' <= c && c <= 'f') || ('A' <= c && c <= 'F')) {
				return false
			}
		}
	}
	return true
}
`

type validateGen struct {
	msgIndex     map[string]ir.Message
	enumIndex    map[string]ir.Enum
	needs        map[string]bool
	patterns     []patternEntry
	patternIndex map[string]string
	needRegexp   bool
	needNetMail  bool
	needFmt      bool
	needUTF8     bool
	needUUID     bool
	needBytes    bool
	needSlices   bool
	needStrings  bool
}

type patternEntry struct {
	Var     string
	Pattern string
}

func (g *validateGen) addPattern(p string) (string, error) {
	if v, ok := g.patternIndex[p]; ok {
		return v, nil
	}
	if _, err := regexp.Compile(p); err != nil {
		return "", fmt.Errorf("invalid pattern %q: %w", p, err)
	}
	v := fmt.Sprintf("validatePattern%d", len(g.patterns))
	g.patterns = append(g.patterns, patternEntry{Var: v, Pattern: p})
	g.patternIndex[p] = v
	g.needRegexp = true
	return v, nil
}

func computeValidateNeeds(msgIndex map[string]ir.Message) map[string]bool {
	needs := map[string]bool{}
	for fullName, msg := range msgIndex {
		for _, field := range msg.Fields {
			if field.GoIgnore {
				continue
			}
			if !field.Constraints.IsEmpty() {
				needs[fullName] = true
				break
			}
		}
	}
	for {
		added := false
		for fullName, msg := range msgIndex {
			if needs[fullName] {
				continue
			}
			for _, field := range msg.Fields {
				if field.GoIgnore {
					continue
				}
				target := validateMessageTarget(field)
				if target != "" && needs[target] {
					needs[fullName] = true
					added = true
					break
				}
			}
		}
		if !added {
			break
		}
	}
	return needs
}

func validateMessageTarget(field ir.Field) string {
	if field.IsMap {
		if field.MapValueKind == ir.KindMessage {
			return field.MapValueMessage
		}
		return ""
	}
	if field.Kind != ir.KindMessage {
		return ""
	}
	if field.IsTimestamp || field.IsDuration {
		return ""
	}
	return field.MessageFullName
}

func (g *validateGen) emitValidate(b *strings.Builder, msg ir.Message) error {
	b.WriteString("func (m *")
	b.WriteString(msg.Name)
	b.WriteString(") Validate() error {\n")
	for _, field := range msg.Fields {
		if field.GoIgnore {
			continue
		}
		if field.Constraints.Ignore == ir.IgnoreAlways {
			continue
		}
		if err := g.emitField(b, field); err != nil {
			return err
		}
	}
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")
	return nil
}

func (g *validateGen) emitField(b *strings.Builder, field ir.Field) error {
	pathExpr := strconv.Quote(fieldProtoName(field))
	receiver := "m." + ir.GoName(field.Name)
	switch {
	case field.IsMap:
		return g.emitMapField(b, field, receiver, pathExpr)
	case field.IsRepeated:
		return g.emitRepeatedField(b, field, receiver, pathExpr)
	case field.Kind == ir.KindMessage && !field.IsTimestamp && !field.IsDuration:
		return g.emitMessageField(b, field, receiver, pathExpr)
	case field.IsOptional:
		return g.emitOptionalScalarField(b, field, receiver, pathExpr)
	default:
		return g.emitScalarField(b, field, receiver, pathExpr)
	}
}

func (g *validateGen) emitRequiredCheck(b *strings.Builder, condExpr, pathExpr string) {
	b.WriteString("\tif ")
	b.WriteString(condExpr)
	b.WriteString(" {\n")
	b.WriteString("\t\treturn newValidationError([]string{")
	b.WriteString(pathExpr)
	b.WriteString("}, \"is required\")\n")
	b.WriteString("\t}\n")
}

func (g *validateGen) emitOptionalScalarField(b *strings.Builder, field ir.Field, receiver, pathExpr string) error {
	cs := field.Constraints
	if cs.Required {
		g.emitRequiredCheck(b, receiver+" == nil", pathExpr)
	}
	if !hasScalarRules(cs) {
		return nil
	}
	b.WriteString("\tif ")
	b.WriteString(receiver)
	b.WriteString(" != nil {\n")
	deref := "(*" + receiver + ")"
	if err := g.emitScalarConstraints(b, field, deref, pathExpr, "\t\t"); err != nil {
		return err
	}
	b.WriteString("\t}\n")
	return nil
}

func (g *validateGen) emitScalarField(b *strings.Builder, field ir.Field, receiver, pathExpr string) error {
	cs := field.Constraints
	if cs.Required {
		cond := zeroValueCondition(field, receiver)
		if cond != "" {
			g.emitRequiredCheck(b, cond, pathExpr)
		}
	}
	if !hasScalarRules(cs) {
		return nil
	}
	indent := "\t"
	guarded := false
	if cs.Ignore == ir.IgnoreIfZeroValue {
		cond := zeroValueCondition(field, receiver)
		if cond != "" {
			b.WriteString("\tif !(")
			b.WriteString(cond)
			b.WriteString(") {\n")
			indent = "\t\t"
			guarded = true
		}
	}
	if err := g.emitScalarConstraints(b, field, receiver, pathExpr, indent); err != nil {
		return err
	}
	if guarded {
		b.WriteString("\t}\n")
	}
	return nil
}

func hasScalarRules(cs ir.FieldConstraints) bool {
	return cs.Numeric != nil || cs.String != nil || cs.Bytes != nil || cs.Bool != nil || cs.Enum != nil
}

func zeroValueCondition(field ir.Field, expr string) string {
	switch field.Kind {
	case ir.KindBool:
		return "!" + expr
	case ir.KindString:
		return expr + ` == ""`
	case ir.KindBytes:
		return "len(" + expr + ") == 0"
	case ir.KindFloat, ir.KindDouble,
		ir.KindInt32, ir.KindInt64, ir.KindSint32, ir.KindSint64,
		ir.KindFixed32, ir.KindFixed64, ir.KindSfixed32, ir.KindSfixed64,
		ir.KindUint32, ir.KindUint64, ir.KindEnum:
		return expr + " == 0"
	case ir.KindMessage:
		return expr + " == nil"
	}
	return ""
}

func (g *validateGen) emitScalarConstraints(b *strings.Builder, field ir.Field, valueExpr, pathExpr, indent string) error {
	cs := field.Constraints
	if cs.Numeric != nil {
		g.emitNumericRules(b, valueExpr, pathExpr, indent, cs.Numeric)
	}
	if cs.String != nil {
		if err := g.emitStringRules(b, valueExpr, pathExpr, indent, cs.String); err != nil {
			return err
		}
	}
	if cs.Bytes != nil {
		if err := g.emitBytesRules(b, valueExpr, pathExpr, indent, cs.Bytes); err != nil {
			return err
		}
	}
	if cs.Bool != nil {
		g.emitBoolRules(b, valueExpr, pathExpr, indent, cs.Bool)
	}
	if cs.Enum != nil {
		g.emitEnumRules(b, field, valueExpr, pathExpr, indent, cs.Enum)
	}
	return nil
}

func (g *validateGen) writeErr(b *strings.Builder, indent, pathExpr, message string) {
	b.WriteString(indent)
	b.WriteString("\treturn newValidationError([]string{")
	b.WriteString(pathExpr)
	b.WriteString("}, ")
	b.WriteString(strconv.Quote(message))
	b.WriteString(")\n")
}

func (g *validateGen) emitNumericRules(b *strings.Builder, valueExpr, pathExpr, indent string, r *ir.NumericRules) {
	emit := func(op, lit, msg string) {
		b.WriteString(indent)
		b.WriteString("if !(")
		b.WriteString(valueExpr)
		b.WriteString(" ")
		b.WriteString(op)
		b.WriteString(" ")
		b.WriteString(lit)
		b.WriteString(") {\n")
		g.writeErr(b, indent, pathExpr, msg+" "+lit)
		b.WriteString(indent)
		b.WriteString("}\n")
	}
	if r.Const != nil {
		emit("==", *r.Const, "must equal")
	}
	if r.Gt != nil {
		emit(">", *r.Gt, "must be greater than")
	}
	if r.Gte != nil {
		emit(">=", *r.Gte, "must be at least")
	}
	if r.Lt != nil {
		emit("<", *r.Lt, "must be less than")
	}
	if r.Lte != nil {
		emit("<=", *r.Lte, "must be at most")
	}
	if len(r.In) > 0 {
		g.needSlices = true
		b.WriteString(indent)
		b.WriteString("if !slices.Contains([]")
		b.WriteString(numericSliceType(r))
		b.WriteString("{")
		b.WriteString(strings.Join(r.In, ", "))
		b.WriteString("}, ")
		b.WriteString(valueExpr)
		b.WriteString(") {\n")
		g.writeErr(b, indent, pathExpr, "must be one of "+strings.Join(r.In, ", "))
		b.WriteString(indent)
		b.WriteString("}\n")
	}
	if len(r.NotIn) > 0 {
		g.needSlices = true
		b.WriteString(indent)
		b.WriteString("if slices.Contains([]")
		b.WriteString(numericSliceType(r))
		b.WriteString("{")
		b.WriteString(strings.Join(r.NotIn, ", "))
		b.WriteString("}, ")
		b.WriteString(valueExpr)
		b.WriteString(") {\n")
		g.writeErr(b, indent, pathExpr, "must not be one of "+strings.Join(r.NotIn, ", "))
		b.WriteString(indent)
		b.WriteString("}\n")
	}
}

// numericSliceType returns the Go literal type to use when emitting an `[]T{...}` literal
// for an in/not_in check. We don't have the field kind here, so we infer from the
// formatted literal: anything containing '.' is float, otherwise int. Untyped constants
// in the slice literal coerce to whatever T resolves to in context, so this is safe.
func numericSliceType(r *ir.NumericRules) string {
	all := append(append([]string(nil), r.In...), r.NotIn...)
	for _, v := range all {
		if strings.ContainsAny(v, ".eE") {
			return "float64"
		}
	}
	return "int64"
}

func (g *validateGen) emitStringRules(b *strings.Builder, valueExpr, pathExpr, indent string, r *ir.StringRules) error {
	if r.Const != nil {
		b.WriteString(indent)
		b.WriteString("if ")
		b.WriteString(valueExpr)
		b.WriteString(" != ")
		b.WriteString(strconv.Quote(*r.Const))
		b.WriteString(" {\n")
		g.writeErr(b, indent, pathExpr, "must equal "+strconv.Quote(*r.Const))
		b.WriteString(indent)
		b.WriteString("}\n")
	}
	if minLen := pickLen(r.Len, r.MinLen); minLen != nil {
		g.needUTF8 = true
		b.WriteString(indent)
		b.WriteString("if utf8.RuneCountInString(")
		b.WriteString(valueExpr)
		b.WriteString(") < ")
		b.WriteString(strconv.FormatUint(*minLen, 10))
		b.WriteString(" {\n")
		g.writeErr(b, indent, pathExpr, fmt.Sprintf("must be at least %d %s", *minLen, pluralize(*minLen, "character", "characters")))
		b.WriteString(indent)
		b.WriteString("}\n")
	}
	if maxLen := pickLen(r.Len, r.MaxLen); maxLen != nil {
		g.needUTF8 = true
		b.WriteString(indent)
		b.WriteString("if utf8.RuneCountInString(")
		b.WriteString(valueExpr)
		b.WriteString(") > ")
		b.WriteString(strconv.FormatUint(*maxLen, 10))
		b.WriteString(" {\n")
		g.writeErr(b, indent, pathExpr, fmt.Sprintf("must be at most %d %s", *maxLen, pluralize(*maxLen, "character", "characters")))
		b.WriteString(indent)
		b.WriteString("}\n")
	}
	if r.Pattern != "" {
		varName, err := g.addPattern(r.Pattern)
		if err != nil {
			return err
		}
		b.WriteString(indent)
		b.WriteString("if !")
		b.WriteString(varName)
		b.WriteString(".MatchString(")
		b.WriteString(valueExpr)
		b.WriteString(") {\n")
		g.writeErr(b, indent, pathExpr, "must match required pattern")
		b.WriteString(indent)
		b.WriteString("}\n")
	}
	if r.Prefix != "" {
		g.needStrings = true
		b.WriteString(indent)
		b.WriteString("if !strings.HasPrefix(")
		b.WriteString(valueExpr)
		b.WriteString(", ")
		b.WriteString(strconv.Quote(r.Prefix))
		b.WriteString(") {\n")
		g.writeErr(b, indent, pathExpr, "must start with "+strconv.Quote(r.Prefix))
		b.WriteString(indent)
		b.WriteString("}\n")
	}
	if r.Suffix != "" {
		g.needStrings = true
		b.WriteString(indent)
		b.WriteString("if !strings.HasSuffix(")
		b.WriteString(valueExpr)
		b.WriteString(", ")
		b.WriteString(strconv.Quote(r.Suffix))
		b.WriteString(") {\n")
		g.writeErr(b, indent, pathExpr, "must end with "+strconv.Quote(r.Suffix))
		b.WriteString(indent)
		b.WriteString("}\n")
	}
	if r.Contains != "" {
		g.needStrings = true
		b.WriteString(indent)
		b.WriteString("if !strings.Contains(")
		b.WriteString(valueExpr)
		b.WriteString(", ")
		b.WriteString(strconv.Quote(r.Contains))
		b.WriteString(") {\n")
		g.writeErr(b, indent, pathExpr, "must contain "+strconv.Quote(r.Contains))
		b.WriteString(indent)
		b.WriteString("}\n")
	}
	if r.NotContains != "" {
		g.needStrings = true
		b.WriteString(indent)
		b.WriteString("if strings.Contains(")
		b.WriteString(valueExpr)
		b.WriteString(", ")
		b.WriteString(strconv.Quote(r.NotContains))
		b.WriteString(") {\n")
		g.writeErr(b, indent, pathExpr, "must not contain "+strconv.Quote(r.NotContains))
		b.WriteString(indent)
		b.WriteString("}\n")
	}
	if len(r.In) > 0 {
		g.needSlices = true
		b.WriteString(indent)
		b.WriteString("if !slices.Contains([]string{")
		for i, s := range r.In {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(strconv.Quote(s))
		}
		b.WriteString("}, ")
		b.WriteString(valueExpr)
		b.WriteString(") {\n")
		g.writeErr(b, indent, pathExpr, "must be one of the allowed values")
		b.WriteString(indent)
		b.WriteString("}\n")
	}
	if len(r.NotIn) > 0 {
		g.needSlices = true
		b.WriteString(indent)
		b.WriteString("if slices.Contains([]string{")
		for i, s := range r.NotIn {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(strconv.Quote(s))
		}
		b.WriteString("}, ")
		b.WriteString(valueExpr)
		b.WriteString(") {\n")
		g.writeErr(b, indent, pathExpr, "must not be one of the disallowed values")
		b.WriteString(indent)
		b.WriteString("}\n")
	}
	if r.Email {
		g.needNetMail = true
		b.WriteString(indent)
		b.WriteString("if _, err := mail.ParseAddress(")
		b.WriteString(valueExpr)
		b.WriteString("); err != nil {\n")
		g.writeErr(b, indent, pathExpr, "must be a valid email address")
		b.WriteString(indent)
		b.WriteString("}\n")
	}
	if r.UUID {
		g.needUUID = true
		b.WriteString(indent)
		b.WriteString("if !validateUUIDFormat(")
		b.WriteString(valueExpr)
		b.WriteString(") {\n")
		g.writeErr(b, indent, pathExpr, "must be a valid UUID")
		b.WriteString(indent)
		b.WriteString("}\n")
	}
	return nil
}

func pickLen(len, oneSided *uint64) *uint64 {
	if len != nil {
		return len
	}
	return oneSided
}

func bytesLiteral(b []byte) string {
	var s strings.Builder
	s.WriteString("[]byte{")
	for i, c := range b {
		if i > 0 {
			s.WriteString(", ")
		}
		s.WriteString(strconv.FormatUint(uint64(c), 10))
	}
	s.WriteString("}")
	return s.String()
}

func (g *validateGen) emitBytesRules(b *strings.Builder, valueExpr, pathExpr, indent string, r *ir.BytesRules) error {
	if r.HasConst {
		g.needBytes = true
		b.WriteString(indent)
		b.WriteString("if !bytes.Equal(")
		b.WriteString(valueExpr)
		b.WriteString(", ")
		b.WriteString(bytesLiteral(r.Const))
		b.WriteString(") {\n")
		g.writeErr(b, indent, pathExpr, "must equal the required bytes")
		b.WriteString(indent)
		b.WriteString("}\n")
	}
	if minLen := pickLen(r.Len, r.MinLen); minLen != nil {
		b.WriteString(indent)
		b.WriteString("if len(")
		b.WriteString(valueExpr)
		b.WriteString(") < ")
		b.WriteString(strconv.FormatUint(*minLen, 10))
		b.WriteString(" {\n")
		g.writeErr(b, indent, pathExpr, fmt.Sprintf("must be at least %d %s", *minLen, pluralize(*minLen, "byte", "bytes")))
		b.WriteString(indent)
		b.WriteString("}\n")
	}
	if maxLen := pickLen(r.Len, r.MaxLen); maxLen != nil {
		b.WriteString(indent)
		b.WriteString("if len(")
		b.WriteString(valueExpr)
		b.WriteString(") > ")
		b.WriteString(strconv.FormatUint(*maxLen, 10))
		b.WriteString(" {\n")
		g.writeErr(b, indent, pathExpr, fmt.Sprintf("must be at most %d %s", *maxLen, pluralize(*maxLen, "byte", "bytes")))
		b.WriteString(indent)
		b.WriteString("}\n")
	}
	if r.Pattern != "" {
		varName, err := g.addPattern(r.Pattern)
		if err != nil {
			return err
		}
		b.WriteString(indent)
		b.WriteString("if !")
		b.WriteString(varName)
		b.WriteString(".Match(")
		b.WriteString(valueExpr)
		b.WriteString(") {\n")
		g.writeErr(b, indent, pathExpr, "must match required pattern")
		b.WriteString(indent)
		b.WriteString("}\n")
	}
	if r.HasPrefix {
		g.needBytes = true
		b.WriteString(indent)
		b.WriteString("if !bytes.HasPrefix(")
		b.WriteString(valueExpr)
		b.WriteString(", ")
		b.WriteString(bytesLiteral(r.Prefix))
		b.WriteString(") {\n")
		g.writeErr(b, indent, pathExpr, "must start with the required bytes")
		b.WriteString(indent)
		b.WriteString("}\n")
	}
	if r.HasSuffix {
		g.needBytes = true
		b.WriteString(indent)
		b.WriteString("if !bytes.HasSuffix(")
		b.WriteString(valueExpr)
		b.WriteString(", ")
		b.WriteString(bytesLiteral(r.Suffix))
		b.WriteString(") {\n")
		g.writeErr(b, indent, pathExpr, "must end with the required bytes")
		b.WriteString(indent)
		b.WriteString("}\n")
	}
	if r.HasContains {
		g.needBytes = true
		b.WriteString(indent)
		b.WriteString("if !bytes.Contains(")
		b.WriteString(valueExpr)
		b.WriteString(", ")
		b.WriteString(bytesLiteral(r.Contains))
		b.WriteString(") {\n")
		g.writeErr(b, indent, pathExpr, "must contain the required bytes")
		b.WriteString(indent)
		b.WriteString("}\n")
	}
	return nil
}

func (g *validateGen) emitBoolRules(b *strings.Builder, valueExpr, pathExpr, indent string, r *ir.BoolRules) {
	if r.Const == nil {
		return
	}
	want := "false"
	if *r.Const {
		want = "true"
	}
	b.WriteString(indent)
	b.WriteString("if ")
	b.WriteString(valueExpr)
	b.WriteString(" != ")
	b.WriteString(want)
	b.WriteString(" {\n")
	g.writeErr(b, indent, pathExpr, "must be "+want)
	b.WriteString(indent)
	b.WriteString("}\n")
}

func (g *validateGen) emitEnumRules(b *strings.Builder, field ir.Field, valueExpr, pathExpr, indent string, r *ir.EnumRules) {
	if r.Const != nil {
		lit := strconv.FormatInt(int64(*r.Const), 10)
		b.WriteString(indent)
		b.WriteString("if int32(")
		b.WriteString(valueExpr)
		b.WriteString(") != ")
		b.WriteString(lit)
		b.WriteString(" {\n")
		g.writeErr(b, indent, pathExpr, "must equal "+lit)
		b.WriteString(indent)
		b.WriteString("}\n")
	}
	if r.DefinedOnly {
		if enum, ok := g.enumIndex[field.EnumFullName]; ok && len(enum.Values) > 0 {
			seen := map[int32]bool{}
			var nums []int32
			for _, v := range enum.Values {
				if seen[v.Number] {
					continue
				}
				seen[v.Number] = true
				nums = append(nums, v.Number)
			}
			b.WriteString(indent)
			b.WriteString("switch int32(")
			b.WriteString(valueExpr)
			b.WriteString(") {\n")
			b.WriteString(indent)
			b.WriteString("case ")
			for i, n := range nums {
				if i > 0 {
					b.WriteString(", ")
				}
				b.WriteString(strconv.FormatInt(int64(n), 10))
			}
			b.WriteString(":\n")
			b.WriteString(indent)
			b.WriteString("default:\n")
			g.writeErr(b, indent, pathExpr, "must be a defined enum value")
			b.WriteString(indent)
			b.WriteString("}\n")
		}
	}
	if len(r.In) > 0 {
		g.needSlices = true
		b.WriteString(indent)
		b.WriteString("if !slices.Contains([]int32{")
		for i, n := range r.In {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(strconv.FormatInt(int64(n), 10))
		}
		b.WriteString("}, int32(")
		b.WriteString(valueExpr)
		b.WriteString(")) {\n")
		g.writeErr(b, indent, pathExpr, "must be one of the allowed values")
		b.WriteString(indent)
		b.WriteString("}\n")
	}
	if len(r.NotIn) > 0 {
		g.needSlices = true
		b.WriteString(indent)
		b.WriteString("if slices.Contains([]int32{")
		for i, n := range r.NotIn {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(strconv.FormatInt(int64(n), 10))
		}
		b.WriteString("}, int32(")
		b.WriteString(valueExpr)
		b.WriteString(")) {\n")
		g.writeErr(b, indent, pathExpr, "must not be one of the disallowed values")
		b.WriteString(indent)
		b.WriteString("}\n")
	}
}

func (g *validateGen) emitMessageField(b *strings.Builder, field ir.Field, receiver, pathExpr string) error {
	cs := field.Constraints
	if cs.Required {
		g.emitRequiredCheck(b, receiver+" == nil", pathExpr)
	}
	target := validateMessageTarget(field)
	if target == "" || !g.needs[target] {
		return nil
	}
	b.WriteString("\tif ")
	b.WriteString(receiver)
	b.WriteString(" != nil {\n")
	b.WriteString("\t\tif err := ")
	b.WriteString(receiver)
	b.WriteString(".Validate(); err != nil {\n")
	b.WriteString("\t\t\treturn wrapValidationError(err, ")
	b.WriteString(pathExpr)
	b.WriteString(")\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	return nil
}

func (g *validateGen) emitRepeatedField(b *strings.Builder, field ir.Field, receiver, pathExpr string) error {
	cs := field.Constraints
	if cs.Required {
		g.emitRequiredCheck(b, "len("+receiver+") == 0", pathExpr)
	}
	if cs.Repeated != nil {
		if cs.Repeated.MinItems != nil {
			n := *cs.Repeated.MinItems
			b.WriteString("\tif len(")
			b.WriteString(receiver)
			b.WriteString(") < ")
			b.WriteString(strconv.FormatUint(n, 10))
			b.WriteString(" {\n")
			g.writeErr(b, "\t", pathExpr, fmt.Sprintf("must contain at least %d %s", n, pluralize(n, "item", "items")))
			b.WriteString("\t}\n")
		}
		if cs.Repeated.MaxItems != nil {
			n := *cs.Repeated.MaxItems
			b.WriteString("\tif len(")
			b.WriteString(receiver)
			b.WriteString(") > ")
			b.WriteString(strconv.FormatUint(n, 10))
			b.WriteString(" {\n")
			g.writeErr(b, "\t", pathExpr, fmt.Sprintf("must contain at most %d %s", n, pluralize(n, "item", "items")))
			b.WriteString("\t}\n")
		}
	}

	target := validateMessageTarget(field)
	hasItemConstraints := cs.Repeated != nil && cs.Repeated.Items != nil && !cs.Repeated.Items.IsEmpty()
	needsRecurseMessage := target != "" && g.needs[target]
	wantUnique := cs.Repeated != nil && cs.Repeated.Unique
	if !hasItemConstraints && !needsRecurseMessage && !wantUnique {
		return nil
	}

	if wantUnique {
		if err := g.emitUniqueCheck(b, field, receiver, pathExpr); err != nil {
			return err
		}
	}

	if !hasItemConstraints && !needsRecurseMessage {
		return nil
	}

	g.needFmt = true
	b.WriteString("\tfor i, item := range ")
	b.WriteString(receiver)
	b.WriteString(" {\n")
	b.WriteString("\t\t_ = i\n")
	itemPath := indexedPathExpr(pathExpr, "%d", "i")
	if needsRecurseMessage {
		b.WriteString("\t\tif item != nil {\n")
		b.WriteString("\t\t\tif err := item.Validate(); err != nil {\n")
		b.WriteString("\t\t\t\treturn wrapValidationError(err, ")
		b.WriteString(itemPath)
		b.WriteString(")\n")
		b.WriteString("\t\t\t}\n")
		b.WriteString("\t\t}\n")
	}
	if hasItemConstraints {
		itemField := elementField(field)
		itemField.Constraints = *cs.Repeated.Items
		if err := g.emitScalarConstraints(b, itemField, "item", itemPath, "\t\t"); err != nil {
			return err
		}
	}
	b.WriteString("\t}\n")
	return nil
}

func (g *validateGen) emitUniqueCheck(b *strings.Builder, field ir.Field, receiver, pathExpr string) error {
	keyType, transform, ok := uniqueKeyShape(field)
	if !ok {
		return fmt.Errorf("repeated.unique not supported for %s element type", field.Name)
	}
	b.WriteString("\t{\n")
	b.WriteString("\t\tseen := make(map[")
	b.WriteString(keyType)
	b.WriteString("]struct{}, len(")
	b.WriteString(receiver)
	b.WriteString("))\n")
	b.WriteString("\t\tfor _, item := range ")
	b.WriteString(receiver)
	b.WriteString(" {\n")
	b.WriteString("\t\t\tk := ")
	b.WriteString(transform)
	b.WriteString("\n")
	b.WriteString("\t\t\tif _, dup := seen[k]; dup {\n")
	g.writeErr(b, "\t\t\t", pathExpr, "must contain unique items")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\tseen[k] = struct{}{}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	return nil
}

// uniqueKeyShape returns the Go map-key type and the Go expression that converts
// "item" into that key. Returns ok=false for element kinds we can't easily compare
// (messages, repeated, maps).
func uniqueKeyShape(field ir.Field) (keyType string, transform string, ok bool) {
	switch field.Kind {
	case ir.KindString:
		return "string", "item", true
	case ir.KindBytes:
		return "string", "string(item)", true
	case ir.KindBool:
		return "bool", "item", true
	case ir.KindInt32, ir.KindSint32, ir.KindSfixed32:
		return "int32", "item", true
	case ir.KindInt64, ir.KindSint64, ir.KindSfixed64:
		return "int64", "item", true
	case ir.KindUint32, ir.KindFixed32:
		return "uint32", "item", true
	case ir.KindUint64, ir.KindFixed64:
		return "uint64", "item", true
	case ir.KindFloat:
		return "float32", "item", true
	case ir.KindDouble:
		return "float64", "item", true
	case ir.KindEnum:
		return "int32", "int32(item)", true
	}
	return "", "", false
}

func (g *validateGen) emitMapField(b *strings.Builder, field ir.Field, receiver, pathExpr string) error {
	cs := field.Constraints
	if cs.Required {
		g.emitRequiredCheck(b, "len("+receiver+") == 0", pathExpr)
	}
	if cs.Map != nil {
		if cs.Map.MinPairs != nil {
			n := *cs.Map.MinPairs
			b.WriteString("\tif len(")
			b.WriteString(receiver)
			b.WriteString(") < ")
			b.WriteString(strconv.FormatUint(n, 10))
			b.WriteString(" {\n")
			g.writeErr(b, "\t", pathExpr, fmt.Sprintf("must contain at least %d %s", n, pluralize(n, "entry", "entries")))
			b.WriteString("\t}\n")
		}
		if cs.Map.MaxPairs != nil {
			n := *cs.Map.MaxPairs
			b.WriteString("\tif len(")
			b.WriteString(receiver)
			b.WriteString(") > ")
			b.WriteString(strconv.FormatUint(n, 10))
			b.WriteString(" {\n")
			g.writeErr(b, "\t", pathExpr, fmt.Sprintf("must contain at most %d %s", n, pluralize(n, "entry", "entries")))
			b.WriteString("\t}\n")
		}
	}

	target := validateMessageTarget(field)
	hasKeyConstraints := cs.Map != nil && cs.Map.Keys != nil && !cs.Map.Keys.IsEmpty()
	hasValueConstraints := cs.Map != nil && cs.Map.Values != nil && !cs.Map.Values.IsEmpty()
	needsRecurseMessage := target != "" && g.needs[target]
	if !hasKeyConstraints && !hasValueConstraints && !needsRecurseMessage {
		return nil
	}

	g.needFmt = true
	b.WriteString("\tfor k, v := range ")
	b.WriteString(receiver)
	b.WriteString(" {\n")
	if !hasKeyConstraints {
		b.WriteString("\t\t_ = k\n")
	}
	if !hasValueConstraints && !needsRecurseMessage {
		b.WriteString("\t\t_ = v\n")
	}
	keyPath := indexedPathExpr(pathExpr, "%v", "k")
	if hasKeyConstraints {
		keyField := mapKeyField(field)
		keyField.Constraints = *cs.Map.Keys
		if err := g.emitScalarConstraints(b, keyField, "k", keyPath, "\t\t"); err != nil {
			return err
		}
	}
	if needsRecurseMessage {
		b.WriteString("\t\tif v != nil {\n")
		b.WriteString("\t\t\tif err := v.Validate(); err != nil {\n")
		b.WriteString("\t\t\t\treturn wrapValidationError(err, ")
		b.WriteString(keyPath)
		b.WriteString(")\n")
		b.WriteString("\t\t\t}\n")
		b.WriteString("\t\t}\n")
	}
	if hasValueConstraints {
		valField := mapValueField(field)
		valField.Constraints = *cs.Map.Values
		if err := g.emitScalarConstraints(b, valField, "v", keyPath, "\t\t"); err != nil {
			return err
		}
	}
	b.WriteString("\t}\n")
	return nil
}

// indexedPathExpr returns a Go expression that yields "<base>[<index-fmt>]" at runtime.
// `pathExpr` is itself a Go expression (typically a quoted literal) yielding the parent path.
// We keep it composable by wrapping with fmt.Sprintf.
func indexedPathExpr(pathExpr, indexFmt, indexExpr string) string {
	base := unquote(pathExpr)
	return "fmt.Sprintf(" + strconv.Quote(base+"["+indexFmt+"]") + ", " + indexExpr + ")"
}

func elementField(field ir.Field) ir.Field {
	out := field
	out.IsRepeated = false
	out.IsPacked = false
	out.IsOptional = false
	out.Constraints = ir.FieldConstraints{}
	return out
}

func mapKeyField(field ir.Field) ir.Field {
	return ir.Field{
		Name:      field.Name,
		ProtoName: field.ProtoName,
		Kind:      field.MapKeyKind,
	}
}

func mapValueField(field ir.Field) ir.Field {
	return ir.Field{
		Name:            field.Name,
		ProtoName:       field.ProtoName,
		Kind:            field.MapValueKind,
		MessageFullName: field.MapValueMessage,
		EnumFullName:    field.MapValueEnum,
	}
}

func unquote(quoted string) string {
	if u, err := strconv.Unquote(quoted); err == nil {
		return u
	}
	return strings.Trim(quoted, `"`)
}

func fieldProtoName(field ir.Field) string {
	if field.ProtoName != "" {
		return field.ProtoName
	}
	return field.Name
}

func pluralize(n uint64, singular, plural string) string {
	if n == 1 {
		return singular
	}
	return plural
}
